import numpy as np
print("Name : ANUMOL THOMAS\nREG no : SJC22MCA-2011\nCourse Code: 20MCA241\nCourse : Data Science Lab\nDate : 10-10-2023")
two_dim_array = np.arange(16).reshape(4, 4)
print("2D Array:")
print(two_dim_array)
print("All elements excluding the first row:")
print(two_dim_array[1:])
print("All elements excluding the last column:")
print(two_dim_array[:, :-1])
print("Elements of the 1st and 2nd column in the 2nd and 3rd row:")
print(two_dim_array[1:3, 0:2])
print("Elements of the 2nd and 3rd column:")
print(two_dim_array[:, 1:3])
print("2nd and 3rd element of the 1st row:")
print(two_dim_array[0, 1:3])
print("Elements from indices 4 to 10 in descending order:")
print(two_dim_array[3:0:-1, 2:0:-1])