import numpy as np
print("Name : ANUMOL THOMAS\nREG no : SJC22MCA-2011\nCourse Code: 20MCA241\nCourse : Data Science Lab\nDate : 10-10-2023")
arr1d = np.array([6, 8, 12, 46, 50])
print("1D Array:")
print(arr1d)
print()
element_to_insert_1d = int(input("Enter an element to insert into the 1D array: "))
index_to_insert_1d = int(input("Enter the index at which to insert the element: "))
arr1d = np.insert(arr1d, index_to_insert_1d, element_to_insert_1d)
print("Updated 1D Array:")
print(arr1d)
print()
arr2d = np.array([[14, 23, 56], [19, 67, 21]])
print("2D Array:")
print(arr2d)
print()
new_row = input("Enter a new row to insert into the 2D array: ").split()
new_row = np.array([int(x) for x in new_row])
index_to_insert_row = int(input("Enter the index at which to insert the new row: "))
arr2d = np.insert(arr2d, index_to_insert_row, new_row, axis=0)
print("\nUpdated 2D Array:")
print(arr2d)