import numpy as np
arr_id=np.array([1,2,3,4,5])
print("Name : ANUMOL THOMAS\nREG no : SJC22MCA-2011\nCourse Code: 20MCA241\nCourse : Data Science Lab\nDate : 10-10-2023")
diagonal_matrix=np.diag(arr_id)
print("oneD array :")
print(arr_id)
print("Diagonal Matrix :")
print(diagonal_matrix)
arr_2d_square=np.array([[1,2,3],[4,5,6],[7,8,9]])
diagonal_elements=np.diag(arr_2d_square)
print("2D square matrix :")
print(arr_2d_square)
print("Diagonal elements :")
print(diagonal_elements)
arr_2d_non_square=np.array([[1,2,3],[4,5,6]])
diagonal_elements_non_square=np.diag(arr_2d_non_square)
print("2D non square matrix :")
print(arr_2d_non_square)
print("Diagonal elements(Non-square) :")
print(diagonal_elements_non_square)