import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x_cube_multiply=np.multiply(x,np.multiply(x,x))
x_cube_operator=x*x*x
x_cube_power=np.power(x,3)
x_cube_double_star=x**3
identity_matrix=np.identity(x.shape[0])
x_power_2=np.power(x,2)
x_power_3=np.power(x,3)
x_power_4=np.power(x,4)
print("Name : ANUMOL THOMAS\nREG no : SJC22MCA-2011\nCourse Code: 20MCA241\nCourse : Data Science Lab\nDate : 10-10-2023")
print("Original matrix x :")
print(x)
print("cubbed matrix(method 1 - multiply()):")
print(x_cube_multiply)
print("cubbed matrix(method 2 - * operator()):")
print(x_cube_operator)
print("cubbed matrix(method 3 - power()):")
print(x_cube_power)
print("cubbed matrix(method 4 - ** operator()):")
print(x_cube_double_star)
print("identity matrix :")
print(identity_matrix)
print("Matrix to different powers :")
print("x^2 :")
print(x_power_2)
print("x^3 :")
print(x_power_3)
print("x^4 :")
print(x_power_4)